nelmio_api_doc:
  documentation:
    info:
      title: 'API Documentation'
      description: 'This is the API documentation for the Payment Processor project.'
      version: '1.0.0'
    servers:
      - url: 'http://localhost:8000'
        description: 'Local Development Server'
  areas:
    path_patterns:
      - ^(?!/(_(error))).*

