parameters:
    shift4_api_key: '%env(SHIFT4_API_KEY)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Application\Service\Payment\Shift4Provider:
        arguments:
            $shift4ApiKey: '%shift4_api_key%'
            $logger: '@logger'

    App\Application\Service\Payment\AciProvider:
        arguments:
            $logger: '@logger'

    App\Application\Command\ProcessPaymentCommand:
        tags: [ 'console.command' ]
        arguments:
            $paymentProviderFactory: '@App\Application\Factory\PaymentProviderFactory'
